[font]
normal = { family = "Monaco Nerd Font" }
bold = { family = "Monaco Nerd Font", style = "Regular" }
italic = { family = "Monaco Nerd Font", style = "Regular" }
bold_italic = { family = "Monaco Nerd Font", style = "Regular" }
size = 14.0

[colors.primary]
background = "#14191f"
foreground = "#ffffff"

[window]
opacity = 0.92

